services:
  database:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data